### PR TITLE
Introduce LGPLv3

### PR DESCRIPTION
**Pull request by lucemans**

### CODE REVIEW

**Review by thejoshuahendrix — APPROVED** [review]
OK then

**Review by Antony1060 — APPROVED** [review]
Alright, sounds nice

**Review by svemat01 — APPROVED** [review]
Looks like the proper license for us :+1:

**Review by Hattorius — APPROVED** [review]
I FIGURED OUT WHEN I GOT OLDER THAT LIFE JUST SUCKS WITH MIT LICENSES
(forgot how the lyrics goes, I'm sorry)

**Pull request merged**
