### PR TITLE
added filelog examples

### PR DESCRIPTION
**Pull request by thejoshuahendrix**
added one simple example and edited readme

### CODE REVIEW

**Comment by lucemans** [comment]
Did your VSCode change all the quotes around 🤔 lol

**Comment by lucemans** [comment]
@svemat01 Could you take care of this PR's Approval?

**Comment by svemat01** [comment]
Did we not change from double quotes to single quotes or does it not apply here?

**Review by svemat01 — APPROVED** [review]
lgtm

**Review by lucemans — APPROVED** [review]
LGTM

**Pull request merged**
